version: '3.7'
services:
  webpack:
    build: .
    image: webpack:1.0
    container_name: webpack
    tty: true
    stdin_open: true
    ports:
      - "8080:8080"
    environment: {}
    volumes:
      - ./:/usr/local/src
    command: "bash -c 'npm i && npm run start'"
